---

# All tasks about variables management

- name: 'INIT | VARIABLES | Check if OS family vars file exists'
  become: False
  stat:
    path: "{{ role_path }}/vars/os_family/{{ ansible_os_family | lower }}.yml"
  register: 'ntp_check_os_family_vars'
  delegate_to: '127.0.0.1'


- name: 'INIT | VARIABLES | Check if OS distribution vars file exists'
  become: False
  stat:
    path: "{{ role_path }}/vars/os_distribution/{{ ansible_distribution | lower }}.yml"
  register: 'ntp_check_os_distribution_vars'
  delegate_to: '127.0.0.1'


- name: 'INIT | VARIABLES | Check if OS release vars file exists'
  become: False
  stat:
    path: "{{ role_path }}/vars/os_distribution/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"
  register: 'ntp_check_os_release_vars'
  delegate_to: '127.0.0.1'


- name: 'INIT | VARIABLES | Load OS family vars file'
  include_vars: "{{ role_path }}/vars/os_family/{{ ansible_os_family | lower }}.yml"
  when: "ntp_check_os_family_vars.stat.exists"


- name: 'INIT | VARIABLES | Load OS distribution vars file'
  include_vars: "{{ role_path }}/vars/os_distribution/{{ ansible_distribution | lower }}.yml"
  when: "ntp_check_os_distribution_vars.stat.exists"


- name: 'INIT | VARIABLES | Load OS release vars file'
  include_vars: "{{ role_path }}/vars/os_distribution/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"
  when: "ntp_check_os_release_vars.stat.exists"




# Debian install tasks

- name: 'INSTALL | APT | Install ntp packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: "{{ ntp_repository_update_cache }}"
    cache_valid_time: "{{ ntp_repository_cache_valid_time }}"
  with_items: "{{ ntp_packages }}"
  become: yes
  notify: 'HANDLER | Restart ntp'



# Configure tasks

- name: 'CONFIG | Generate ntp config file'
  template:
    src: "{{ role_path }}/templates/ntp/ntp.conf.j2"
    dest: "{{ ntp_config_file_dest }}"
    owner: "{{ ntp_config_file_owner }}"
    group: "{{ ntp_config_file_group }}"
    mode: "{{ ntp_config_file_mode }}"
  notify: 'HANDLER | Restart ntp'
  become: yes


- name: 'CONFIG | Manage ntp service'
  become: yes
  service:
    name: "{{ ntp_service.name }}"
    enabled: "{{ ntp_service.enabled }}"
    state: "{{ ntp_service.state }}"
